apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 0.6.0
    helm:
      parameters:
        - name: alloy.configMap.create
          value: "false"
        - name: alloy.configMap.name
          value: alloy
        - name: alloy.configMap.key
          value: config.alloy
        - name: alloy.controller.type
          value: daemonset
        - name: alloy.mounts.varlog
          value: "true"
        - name: alloy.mounts.dockercontainers
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
