apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: mimir-distributed
    targetRevision: 5.4.0
    helm:
      values: |
        mimir:
          structuredConfig:
            usage_stats:
              enabled: false
            common:
              storage:
                backend: filesystem
                filesystem:
                  dir: /data/mimir
            blocks_storage:
              backend: filesystem
              filesystem:
                dir: /data/mimir/blocks
            compactor:
              data_dir: /data/mimir/compactor
            ingester:
              ring:
                replication_factor: 1
            store_gateway:
              sharding_ring:
                replication_factor: 1
        minio:
          enabled: true
        ingester:
          replicas: 1
          zoneAwareReplication:
            enabled: false
        store_gateway:
          zoneAwareReplication:
            enabled: false
        distributor:
          replicas: 1
        querier:
          replicas: 1
        query_frontend:
          replicas: 1
        compactor:
          replicas: 1
        ruler:
          enabled: false
        alertmanager:
          enabled: false
        rollout_operator:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
