apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sudheer52/lgtm-platform.git
    targetRevision: HEAD
    path: apps/sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: tns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
